### ISSUE TITLE
Can u pls help me with this error!! I saw ur project is running fine but I am getting this mongo db error. a month ago, my server was running fine but now it is not and I haven't changed a setting

### ISSUE THREAD

**Issue by Prantik-Barik** [Hruthik-28/youtube-twitter#1]
MONGODB connection error MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is 
on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
    at _handleConnectionErrors (C:\Users\KIIT\OneDrive\Desktop\Backend-Project\node_modules\mongoose\lib\connection.js:875:11) 
    at NativeConnection.openUri (C:\Users\KIIT\OneDrive\Desktop\Backend-Project\node_modules\mongoose\lib\connection.js:826:11)    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async connectDB (file:///C:/Users/KIIT/OneDrive/Desktop/Backend-Project/src/db/index.js:6:36) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-ccb8zeb-shard-00-00.bzh1xn1.mongodb.net:27017' => [ServerDescription],
      'ac-ccb8zeb-shard-00-01.bzh1xn1.mongodb.net:27017' => [ServerDescription],
      'ac-ccb8zeb-shard-00-02.bzh1xn1.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-n0rk60-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

**Comment by atharva160902** [comment]
You have to whitelist your IP address in MongoDB atlas .
1 Go to MongoDB atlas
2 Click on network access tab
3 whitelist your IP or simply you can put 0.0.0.0/0 in IP access list

**Comment by Shivamxeric** [comment]
i will fix that bug

**Comment by manoj-jm** [comment]
hey @Hruthik-28 , did that bug get fixed ???
